Update Resource Pool API to include type attribute
ManageIQ/manageiq-api pull request #1248
Opened 2024-02-19 12:20 UTC by Guddetisandeep

2024-02-19 12:37 UTC, Guddetisandeep commented
The query returns only the resource pools associated with cloud management when the `type` attribute is used with the specified class `(ManageIQ::Providers::CloudManager::ResourcePool)`
```
curl -s -X GET -H "X-Auth-Token: $(miq_auth_token)" -H "Accept: application/json" "http://localhost:3000/api/resource_pools?type=ManageIQ::Providers::CloudManager::ResourcePool" | jq .
{
  "name": "resource_pools",
  "count": 142,
  "subcount": 1,
  "subquery_count": 1,
  "pages": 1,
  "resources": [
    {
      "href": "http://localhost:3000/api/resource_pools/162"
    }
  ],
  "actions": [
    {
      "name": "query",
      "method": "post",
      "href": "http://localhost:3000/api/resource_pools"
    }
  ],
  "links": {
    "self": "http://localhost:3000/api/resource_pools?type=ManageIQ::Providers::CloudManager::ResourcePool&offset=0",
    "first": "http://localhost:3000/api/resource_pools?type=ManageIQ::Providers::CloudManager::ResourcePool&offset=0",
    "last": "http://localhost:3000/api/resource_pools?type=ManageIQ::Providers::CloudManager::ResourcePool&offset=0"
  }
}
```

2024-02-21 18:41 UTC, Fryguy commented on app/controllers/api/resource_pools_controller.rb
> +    def fetch_resource_pools_by_type(type)
This is not the right way to do this.  I would expect a type parmeter incoming that lists the type you need, and then it's a normal STI query.

2024-04-05 15:10 UTC, Fryguy commented
@Guddetisandeep - We found there's a better way to do this than using a type filter.  Instead, pass a `collection_class` parameter at the same level as the filter.

2024-04-05 16:59 UTC, Fryguy requested changes
I think we can close this PR, and the callers can use `collection_class` instead, which should already work for ResourcePools.

2024-04-08 02:48 UTC, Guddetisandeep commented
Closing this PR using `collection_class` instead of the type filter.

2024-04-08 02:48 UTC, closed without merging